//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.11.17 at 09:26:47 AM AWST 
//


package org.csiro.igsn.bindings.allocation2_0;



/**
 * <p>Java class for nilReasonType.
 * 
 
 * 
 */
public enum NilReasonType {

   
    INAPPLICABLE("http://www.opengis.net/def/nil/OGC/0/inapplicable"),    
    MISSING("http://www.opengis.net/def/nil/OGC/0/missing"),   
    TEMPLATE("http://www.opengis.net/def/nil/OGC/0/template"),   
    UNKNOWN("http://www.opengis.net/def/nil/OGC/0/unknown"),  
    WITHHELD("http://www.opengis.net/def/nil/OGC/0/withheld");
    
    private final String value;

    NilReasonType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static NilReasonType fromValue(String v) {
        for (NilReasonType c: NilReasonType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }
    
    public static boolean match(String v) {
        for (NilReasonType c: NilReasonType.values()) {
            if (c.value.equals(v)) {
                return true;
            }
        }
        return false;
        
    }

}
