//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.11.26 at 09:11:18 AM AWST 
//


package org.csiro.igsn.bindings.allocation2_0;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for spatialType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="spatialType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="Point"/>
 *     &lt;enumeration value="Linestring"/>
 *     &lt;enumeration value="MultiPoint"/>
 *     &lt;enumeration value="Polygon"/>
 *     &lt;enumeration value="Geometry"/>
 *     &lt;enumeration value="Geometry Collection"/>
 *     &lt;enumeration value="Curve"/>
 *     &lt;enumeration value="Line"/>
 *     &lt;enumeration value="LinearRing"/>
 *     &lt;enumeration value="MultiCurve"/>
 *     &lt;enumeration value="MultiLineString"/>
 *     &lt;enumeration value="Surface"/>
 *     &lt;enumeration value="MultiSurface"/>
 *     &lt;enumeration value="MultiPolygon"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "spatialType")
@XmlEnum
public enum SpatialType {

    @XmlEnumValue("Point")
    POINT("Point"),
    @XmlEnumValue("Linestring")
    LINESTRING("Linestring"),
    @XmlEnumValue("MultiPoint")
    MULTI_POINT("MultiPoint"),
    @XmlEnumValue("Polygon")
    POLYGON("Polygon"),
    @XmlEnumValue("Geometry")
    GEOMETRY("Geometry"),
    @XmlEnumValue("Geometry Collection")
    GEOMETRY_COLLECTION("Geometry Collection"),
    @XmlEnumValue("Curve")
    CURVE("Curve"),
    @XmlEnumValue("Line")
    LINE("Line"),
    @XmlEnumValue("LinearRing")
    LINEAR_RING("LinearRing"),
    @XmlEnumValue("MultiCurve")
    MULTI_CURVE("MultiCurve"),
    @XmlEnumValue("MultiLineString")
    MULTI_LINE_STRING("MultiLineString"),
    @XmlEnumValue("Surface")
    SURFACE("Surface"),
    @XmlEnumValue("MultiSurface")
    MULTI_SURFACE("MultiSurface"),
    @XmlEnumValue("MultiPolygon")
    MULTI_POLYGON("MultiPolygon");
    private final String value;

    SpatialType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static SpatialType fromValue(String v) {
        for (SpatialType c: SpatialType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
