//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.02.21 at 12:26:25 PM AWST 
//


package org.csiro.igsn.jaxb.oai.bindings.igsn;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for materialType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="materialType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="http://vocabulary.odm2.org/medium/air/"/>
 *     &lt;enumeration value="http://vocabulary.odm2.org/medium/gas/"/>
 *     &lt;enumeration value="http://vocabulary.odm2.org/medium/ice/"/>
 *     &lt;enumeration value="http://vocabulary.odm2.org/medium/liquidAqueous/"/>
 *     &lt;enumeration value="http://vocabulary.odm2.org/medium/liquidOrganic/"/>
 *     &lt;enumeration value="http://vocabulary.odm2.org/medium/mineral/"/>
 *     &lt;enumeration value="http://vocabulary.odm2.org/medium/organism/"/>
 *     &lt;enumeration value="http://vocabulary.odm2.org/medium/particulate/"/>
 *     &lt;enumeration value="http://vocabulary.odm2.org/medium/rock/"/>
 *     &lt;enumeration value="http://vocabulary.odm2.org/medium/sediment/"/>
 *     &lt;enumeration value="http://vocabulary.odm2.org/medium/snow/"/>
 *     &lt;enumeration value="http://vocabulary.odm2.org/medium/soil/"/>
 *     &lt;enumeration value="http://vocabulary.odm2.org/medium/tissue/"/>
 *     &lt;enumeration value="http://vocabulary.odm2.org/medium/other/"/>
 *     &lt;enumeration value="http://vocabulary.odm2.org/medium/unknown/"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "materialType")
@XmlEnum
public enum MaterialType {

    @XmlEnumValue("http://vocabulary.odm2.org/medium/air/")
    HTTP_VOCABULARY_ODM_2_ORG_MEDIUM_AIR("http://vocabulary.odm2.org/medium/air/"),
    @XmlEnumValue("http://vocabulary.odm2.org/medium/gas/")
    HTTP_VOCABULARY_ODM_2_ORG_MEDIUM_GAS("http://vocabulary.odm2.org/medium/gas/"),
    @XmlEnumValue("http://vocabulary.odm2.org/medium/ice/")
    HTTP_VOCABULARY_ODM_2_ORG_MEDIUM_ICE("http://vocabulary.odm2.org/medium/ice/"),
    @XmlEnumValue("http://vocabulary.odm2.org/medium/liquidAqueous/")
    HTTP_VOCABULARY_ODM_2_ORG_MEDIUM_LIQUID_AQUEOUS("http://vocabulary.odm2.org/medium/liquidAqueous/"),
    @XmlEnumValue("http://vocabulary.odm2.org/medium/liquidOrganic/")
    HTTP_VOCABULARY_ODM_2_ORG_MEDIUM_LIQUID_ORGANIC("http://vocabulary.odm2.org/medium/liquidOrganic/"),
    @XmlEnumValue("http://vocabulary.odm2.org/medium/mineral/")
    HTTP_VOCABULARY_ODM_2_ORG_MEDIUM_MINERAL("http://vocabulary.odm2.org/medium/mineral/"),
    @XmlEnumValue("http://vocabulary.odm2.org/medium/organism/")
    HTTP_VOCABULARY_ODM_2_ORG_MEDIUM_ORGANISM("http://vocabulary.odm2.org/medium/organism/"),
    @XmlEnumValue("http://vocabulary.odm2.org/medium/particulate/")
    HTTP_VOCABULARY_ODM_2_ORG_MEDIUM_PARTICULATE("http://vocabulary.odm2.org/medium/particulate/"),
    @XmlEnumValue("http://vocabulary.odm2.org/medium/rock/")
    HTTP_VOCABULARY_ODM_2_ORG_MEDIUM_ROCK("http://vocabulary.odm2.org/medium/rock/"),
    @XmlEnumValue("http://vocabulary.odm2.org/medium/sediment/")
    HTTP_VOCABULARY_ODM_2_ORG_MEDIUM_SEDIMENT("http://vocabulary.odm2.org/medium/sediment/"),
    @XmlEnumValue("http://vocabulary.odm2.org/medium/snow/")
    HTTP_VOCABULARY_ODM_2_ORG_MEDIUM_SNOW("http://vocabulary.odm2.org/medium/snow/"),
    @XmlEnumValue("http://vocabulary.odm2.org/medium/soil/")
    HTTP_VOCABULARY_ODM_2_ORG_MEDIUM_SOIL("http://vocabulary.odm2.org/medium/soil/"),
    @XmlEnumValue("http://vocabulary.odm2.org/medium/tissue/")
    HTTP_VOCABULARY_ODM_2_ORG_MEDIUM_TISSUE("http://vocabulary.odm2.org/medium/tissue/"),
    @XmlEnumValue("http://vocabulary.odm2.org/medium/other/")
    HTTP_VOCABULARY_ODM_2_ORG_MEDIUM_OTHER("http://vocabulary.odm2.org/medium/other/"),
    @XmlEnumValue("http://vocabulary.odm2.org/medium/unknown/")
    HTTP_VOCABULARY_ODM_2_ORG_MEDIUM_UNKNOWN("http://vocabulary.odm2.org/medium/unknown/");
    private final String value;

    MaterialType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static MaterialType fromValue(String v) {
        for (MaterialType c: MaterialType.values()) {
            if (c.value.equalsIgnoreCase(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
