//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.02.21 at 12:26:25 PM AWST 
//


package org.csiro.igsn.jaxb.oai.bindings.igsn;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.csiro.igsn.jaxb.oai.bindings.igsn package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.csiro.igsn.jaxb.oai.bindings.igsn
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Resource }
     * 
     */
    public Resource createResource() {
        return new Resource();
    }

    /**
     * Create an instance of {@link Resource.SupplementalMetadata }
     * 
     */
    public Resource.SupplementalMetadata createResourceSupplementalMetadata() {
        return new Resource.SupplementalMetadata();
    }

    /**
     * Create an instance of {@link Resource.Contributors }
     * 
     */
    public Resource.Contributors createResourceContributors() {
        return new Resource.Contributors();
    }

    /**
     * Create an instance of {@link Resource.Contributors.Contributor }
     * 
     */
    public Resource.Contributors.Contributor createResourceContributorsContributor() {
        return new Resource.Contributors.Contributor();
    }

    /**
     * Create an instance of {@link Resource.Collectors }
     * 
     */
    public Resource.Collectors createResourceCollectors() {
        return new Resource.Collectors();
    }

    /**
     * Create an instance of {@link Resource.Collectors.Collector }
     * 
     */
    public Resource.Collectors.Collector createResourceCollectorsCollector() {
        return new Resource.Collectors.Collector();
    }

    /**
     * Create an instance of {@link Resource.Collectors.Collector.Affiliation }
     * 
     */
    public Resource.Collectors.Collector.Affiliation createResourceCollectorsCollectorAffiliation() {
        return new Resource.Collectors.Collector.Affiliation();
    }

    /**
     * Create an instance of {@link Resource.CollectionMethods }
     * 
     */
    public Resource.CollectionMethods createResourceCollectionMethods() {
        return new Resource.CollectionMethods();
    }

    /**
     * Create an instance of {@link Resource.Date }
     * 
     */
    public Resource.Date createResourceDate() {
        return new Resource.Date();
    }

    /**
     * Create an instance of {@link Resource.Locations }
     * 
     */
    public Resource.Locations createResourceLocations() {
        return new Resource.Locations();
    }

    /**
     * Create an instance of {@link Resource.Locations.Toponym }
     * 
     */
    public Resource.Locations.Toponym createResourceLocationsToponym() {
        return new Resource.Locations.Toponym();
    }

    /**
     * Create an instance of {@link Resource.Materials }
     * 
     */
    public Resource.Materials createResourceMaterials() {
        return new Resource.Materials();
    }

    /**
     * Create an instance of {@link Resource.ResourceTypes }
     * 
     */
    public Resource.ResourceTypes createResourceResourceTypes() {
        return new Resource.ResourceTypes();
    }

    /**
     * Create an instance of {@link Resource.Registrant }
     * 
     */
    public Resource.Registrant createResourceRegistrant() {
        return new Resource.Registrant();
    }

    /**
     * Create an instance of {@link Resource.Registrant.Affiliation }
     * 
     */
    public Resource.Registrant.Affiliation createResourceRegistrantAffiliation() {
        return new Resource.Registrant.Affiliation();
    }

    /**
     * Create an instance of {@link Resource.RelatedResources }
     * 
     */
    public Resource.RelatedResources createResourceRelatedResources() {
        return new Resource.RelatedResources();
    }

    /**
     * Create an instance of {@link Resource.AlternateIdentifiers }
     * 
     */
    public Resource.AlternateIdentifiers createResourceAlternateIdentifiers() {
        return new Resource.AlternateIdentifiers();
    }

    /**
     * Create an instance of {@link Resource.Identifier }
     * 
     */
    public Resource.Identifier createResourceIdentifier() {
        return new Resource.Identifier();
    }

    /**
     * Create an instance of {@link Resource.SupplementalMetadata.Metadata }
     * 
     */
    public Resource.SupplementalMetadata.Metadata createResourceSupplementalMetadataMetadata() {
        return new Resource.SupplementalMetadata.Metadata();
    }

    /**
     * Create an instance of {@link Resource.Contributors.Contributor.Identifier }
     * 
     */
    public Resource.Contributors.Contributor.Identifier createResourceContributorsContributorIdentifier() {
        return new Resource.Contributors.Contributor.Identifier();
    }

    /**
     * Create an instance of {@link Resource.Collectors.Collector.Identifier }
     * 
     */
    public Resource.Collectors.Collector.Identifier createResourceCollectorsCollectorIdentifier() {
        return new Resource.Collectors.Collector.Identifier();
    }

    /**
     * Create an instance of {@link Resource.Collectors.Collector.Affiliation.Identifier }
     * 
     */
    public Resource.Collectors.Collector.Affiliation.Identifier createResourceCollectorsCollectorAffiliationIdentifier() {
        return new Resource.Collectors.Collector.Affiliation.Identifier();
    }

    /**
     * Create an instance of {@link Resource.CollectionMethods.AlternateCollectionMethods }
     * 
     */
    public Resource.CollectionMethods.AlternateCollectionMethods createResourceCollectionMethodsAlternateCollectionMethods() {
        return new Resource.CollectionMethods.AlternateCollectionMethods();
    }

    /**
     * Create an instance of {@link Resource.Date.TimePeriod }
     * 
     */
    public Resource.Date.TimePeriod createResourceDateTimePeriod() {
        return new Resource.Date.TimePeriod();
    }

    /**
     * Create an instance of {@link Resource.Locations.Geometry }
     * 
     */
    public Resource.Locations.Geometry createResourceLocationsGeometry() {
        return new Resource.Locations.Geometry();
    }

    /**
     * Create an instance of {@link Resource.Locations.Toponym.Identifier }
     * 
     */
    public Resource.Locations.Toponym.Identifier createResourceLocationsToponymIdentifier() {
        return new Resource.Locations.Toponym.Identifier();
    }

    /**
     * Create an instance of {@link Resource.Materials.AlternateMaterials }
     * 
     */
    public Resource.Materials.AlternateMaterials createResourceMaterialsAlternateMaterials() {
        return new Resource.Materials.AlternateMaterials();
    }

    /**
     * Create an instance of {@link Resource.ResourceTypes.AlternateResourceTypes }
     * 
     */
    public Resource.ResourceTypes.AlternateResourceTypes createResourceResourceTypesAlternateResourceTypes() {
        return new Resource.ResourceTypes.AlternateResourceTypes();
    }

    /**
     * Create an instance of {@link Resource.Registrant.Identifier }
     * 
     */
    public Resource.Registrant.Identifier createResourceRegistrantIdentifier() {
        return new Resource.Registrant.Identifier();
    }

    /**
     * Create an instance of {@link Resource.Registrant.Affiliation.Identifier }
     * 
     */
    public Resource.Registrant.Affiliation.Identifier createResourceRegistrantAffiliationIdentifier() {
        return new Resource.Registrant.Affiliation.Identifier();
    }

    /**
     * Create an instance of {@link Resource.RelatedResources.RelatedResource }
     * 
     */
    public Resource.RelatedResources.RelatedResource createResourceRelatedResourcesRelatedResource() {
        return new Resource.RelatedResources.RelatedResource();
    }

    /**
     * Create an instance of {@link Resource.AlternateIdentifiers.AlternateIdentifier }
     * 
     */
    public Resource.AlternateIdentifiers.AlternateIdentifier createResourceAlternateIdentifiersAlternateIdentifier() {
        return new Resource.AlternateIdentifiers.AlternateIdentifier();
    }

}
